const actions = {
  INIT_GAPI_SUCCESS: 'INIT_GAPI_SUCCESS',
  INIT_GAPI_FAILURE: 'INIT_GAPI_FAILURE',

  FETCH_CITY: 'FETCH_CITY',
  FETCH_CITY_SUCCESS: 'FETCH_CITY_SUCCESS',
  FETCH_CITY_FAILURE: 'FETCH_CITY_FAILURE',
};

export default actions;
